FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    nginx \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install pdo pdo_mysql mbstring zip

COPY . /var/www

WORKDIR /var/www

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN chown -R www-data:www-data /var/www && chmod -R 755 /var/www

EXPOSE 80

CMD service nginx start && php-fpm
