name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: List build output
        run: ls -la public/build

      - name: Archive build directory
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: public/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: b12_37391677
          password: ${{ secrets.ftp_password }}
          local-dir: build/
          server-dir: /filmo.celemin.me/htdocs/public/build/
          dangerous-clean-slate: true
