name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build dependencies
        run: npm run build

      - name: List build output
        run: ls -la dist  # Verifica que los archivos estén en dist

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist  # Asegúrate de que el nombre coincida con lo que usas para descargarlo
          path: dist  # Ruta donde se encuentra la salida de los archivos generados

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ftpupload.net
          username: b12_37391677
          password: ${{ secrets.ftp_password }}
          local-dir: dist
